# Travis is now container based which doesn't support sudo
sudo: false
language: csharp
solution: Polaroider.sln
mono: none
dotnet: 3.1

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: never #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always

install:
  - sudo apt-get install -qq dotnet-sdk-2.0.0
  - dotnet restore Polaroider.sln
  - nvm install 10.0.0
  - nvm use 10.0.0

script:
  - dotnet build Polaroider.sln
  - dotnet test Polaroider.sln

addons:
  sonarcloud:
    organization: "wickedflame"
#    token:
#      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner